#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "slrp-trigger-dev"
primary_region = "mia"

[build]
  image = "ghcr.io/triggerdotdev/trigger.dev:latest"

[env]
  REMIX_APP_PORT = "3030"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.http_health_check]
    port = 3030
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/healthcheck"
